desc dept
desc emp
desc salgrade

-- clauzele Where, ORDER BY pot lipsi
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL > 1400
ORDER BY SAL DESC, ENAME;

-- WHERE LOC='CHICAGO';
SELECT * FROM DEPT
WHERE LOC LIKE '%A%';

-- WHERE MGR = 7902
SELECT * FROM EMP
WHERE MGR IN (7902, 7910)
ORDER BY SAL DESC;

CREATE TABLE SALARIATI_BINE_PLATITI
AS
SELECT * FROM EMP
WHERE SAL > &&SALARIU;

SELECT * FROM SALARIATI_BINE_PLATITI;
DROP TABLE SALARIATI_BINE_PLATITI;

-- undefine SALARIU;
-- tabela continand toti subordonatii angaatului cu id 7839
CREATE TABLE SUBORDONATI
AS
SELECT * FROM EMP
WHERE MGR = 7839;

SELECT * FROM SUBORDONATI;

DROP TABLE SUBORDONATI;

SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('01-03-1981', 'DD-MM-YYYY');

SELECT * FROM EMP WHERE TO_CHAR(hiredate, 'DD-MM-YYY') = '20-02-1981';

-- sau LIKE '%1981'
-- Angajati in anii '80 -> LIKE '%198%'

SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('01-03-1981', 'DD-MM-YYYY');

SELECT * FROM EMP WHERE TO_CHAR(hiredate, 'MM-YYYY') LIKE '02-1981';

SELECT * FROM emp
WHERE
HIREDATE BETWEEN TO_CHAR('1981-04-02','YYYY-MM-DD') AND TO_CHAR('1981-12-02','YYYY-MM-DD');


select * FROM EMP WHERE COMM IS NOT NULL AND COMM > 0;
select * FROM EMP WHERE NOT (COMM IS NOT NULL AND COMM > 0);
select * FROM EMP WHERE COMM IS NULL OR (COMM = 0 AND COMM IS NOT NULL);

select 1 from emp;
select 'ANGAJATUL CU ID '|| EMPNO || ' SE NUMESTE ' 
|| ENAME, SAL, DEPTNO, ' AZ ESTE DATA DE ' || SYSDATE
FROM EMP WHERE SAL > 1000;

-- Jonctiunea intre 2 tabele
SELECT EMP.EMPNO, EMP.SAL, EMP.ENAME
FROM EMP, DEPT
WHERE
	EMP.DEPTNO = DEPT.DEPTNO
	AND
	DEPT.LOC LIKE 'CHICAGO';
	
select id_ang AS pin, nume FROM angajati where id_ang IN (7499, 7902, 7876);